language: node_js
node_js:
 - node

dist: bionic
sudo: required

branches:
 only:
  - master

before_script:
 - npm install -g @angular/cli
 - npm i -g now

script:
 - ng build --prod --base-href https://melvinyit.github.io/weather-app/
 - ng build --prod --output-path ./dist/ziet --base-href https://ziet.melvinyit.now.sh/

notifications:
  slack: csf-2019:tYjerA27KoMXFw68mBEyyULT

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/weather-app
  on:
    branch: master

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master