language: node_js
node_js:
 - node

dist: bionic
sudo: required

branches:
 only:
  - master

before_script:
 - npm install -g @angular/cli

script:
 - npm run test-headless
 - ng build --prod --base-href https://melvinyit.github.io/weather-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/weather-app
  on:
    branch: master